# Generated by Django 4.1.7 on 2023-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_user_username', models.CharField(max_length=64, unique=True)),
                ('temp_user_email', models.CharField(max_length=128, unique=True)),
                ('temp_user_password1', models.CharField(max_length=32)),
                ('temp_user_password2', models.CharField(max_length=32)),
                ('super_token', models.CharField(max_length=12)),
            ],
        ),
    ]
