# Generated by Django 4.1.7 on 2023-02-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_alter_ads_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ['-time_creation'], 'verbose_name': 'Пост'},
        ),
        migrations.AddField(
            model_name='ads',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
